version: '3.8'
services:
  db:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres_12_4:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'root0000'
volumes:
  postgres_12_4:
