version: '3.8'
services:
  mysql_5_7_31:
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33060:3306
    volumes:
      - type: volume
        source: mysql_5_7_31
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root0000
  # mysql:
  #   build:
  #     context: .
  #     dockerfile: ./docker/mysql/Dockerfile
  #   command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./:/app
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'pass'
volumes:
  mysql_5_7_31:
