version: '3.8'
services:
  postgres_12_4:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres_12_4:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'root0000'
  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_6:/data
    ports:
      - 6379:6379
volumes:
  postgres_12_4:
  redis_6:
